server_token = 'AAAAg9lrOWo:APA91bGQ9phil8jX2QkmkT8HtvwrS_lcLt5Yk23HXWC9nheztcUm6dRBxVjXFJ6pOhYtuG7pYJoxg-Ld2ok730c-y4ZEM9B8olKHGiKw490s86lUF-HmCZr_ftI5L768QgLIxIGmNE2y'
device_token = 'cteGShZ8QaeT6SQJfLiLH5:APA91bE6PkYdI0aQRH2WeyNYqmS9OMr4Z7K8cATQmY3z8zBMAq7ijhzd3tDpP50qnk2EmKCocxL7p_uoJ_rdPDqtsTOMaffGbm-AmRySGjQ1KxTNi0rJ477TBl0lIhgWKf0_XHBe2rMl'

departments = [
        {
            'name': 'Mühendislik Fakültesi Anasayfası',
            'url': 'https://mf.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://mf.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_anasayfa.json'
        },
        {
            'name': 'Bilgisayar Mühendisliği',
            'url': 'https://bm.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://bm.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a:link',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_bilgisayar.json'
        },
        {
            'name': 'Biyomedikal Mühendisliği',
            'url': 'https://biomed.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://biomed.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_biyomedikal.json'
        },
        {
            'name': 'Çevre Mühendisliği',
            'url': 'https://cevre.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://cevre.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_cevre.json'
        },
        {
            'name': 'Elektrik-Elektronik Mühendisliği',
            'url': 'https://em.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://em.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_elektrik_elektronik.json'
        },
        {
            'name': 'Endüstri Mühendisliği',
            'url': 'https://endustri.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://endustri.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_endustri.json'
        },
        {
            'name': 'Endüstriyel Tasarım Mühendisliği',
            'url': 'https://etm.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://etm.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_endustriyel_tasarim.json'
        },
        {
            'name': 'Enerji Sistemleri Mühendisliği',
            'url': 'https://esm.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://esm.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_enerji_sistemleri.json'
        },
        {
            'name': 'Gıda Mühendisliği',
            'url': 'https://gida.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://gida.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_gida.json'
        },
        {
            'name': 'Harita Mühendisliği',
            'url': 'https://harita.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://harita.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_harita.json'
        },
        {
            'name': 'İnşaat Mühendisliği',
            'url': 'https://insaat.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://insaat.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_insaat.json'
        },
        {
            'name': 'Makine Mühendisliği',
            'url': 'https://me.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://me.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_makine.json'
        },
        {
            'name': 'Malzeme Bilimi Mühendisliği',
            'url': 'https://mbm.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://mbm.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_malzeme.json'
        },
        {
            'name': 'Mekatronik Mühendisliği',
            'url': 'https://mekatronik.erciyes.edu.tr/?Anasayfa',
            'startingLink': 'https://mekatronik.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_mekatronik.json'
        },
        {
            'name': 'Tekstil Mühendisliği',
            'url': 'https://tekstil.erciyes.edu.tr',
            'startingLink': 'https://tekstil.erciyes.edu.tr/',
            'titleSelector': 'h5.post-title > a.font-13',
            'linkSelector': 'h5.post-title > a',
            'dateSelector': 'tr > td.font-12',
            'fileName': 'erciyes_muhendislik_tekstil.json'
        },
        {
            'name': 'Diş Hekimliği Fakültesi',
            'url': 'http://dent.erciyes.edu.tr/Duyuru_Tumu.aspx',
            'startingLink': 'http://dent.erciyes.edu.tr/',
            'titleSelector': 'div.post-right > h5.mt-0 > a',
            'linkSelector': 'div.post-right > h5.mt-0 > a',
            'dateSelector': 'li.pr-0 > span',
            'fileName': 'erciyes_fakulte_dis_hekimligi.json',
        },
        {
            'name': 'Eczacılık Fakültesi',
            'url': 'https://pharmacy.erciyes.edu.tr',
            'startingLink': 'https://pharmacy.erciyes.edu.tr/',
            'titleSelector': 'span.aciklama >  a',
            'linkSelector': 'span.aciklama >  a',
            'dateSelector': 'span.img > span.gun',
            'dateSelector2': 'span.img > span.ay',
            'dateSelector3': 'span.img > span.yil',
            'fileName': 'erciyes_fakulte_eczacilik.json',
        },
        {
            'name': 'Edebiyat Fakültesi',
            'url': 'https://edebiyat.erciyes.edu.tr/',
            'startingLink': 'https://edebiyat.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_fakulte_edebiyat.json',
        },
        {
            'name': 'Eğitim Fakültesi Anasayfası',
            'url': 'http://egitim.erciyes.edu.tr',
            'startingLink': 'http://egitim.erciyes.edu.tr',
            'titleSelector': 'div.news-content-holder > h3 > a > span',
            'linkSelector': 'div.news-content-holder > h3 > a',
            'dateSelector': 'div.post-date > span',
            'fileName': 'erciyes_fakulte_egitim_anasayfa.json',

        },
        {
            'name': 'Eğitim Bilimleri',
            'url': 'http://egt.egitim.erciyes.edu.tr',
            'startingLink': 'http://egt.egitim.erciyes.edu.tr',
            'titleSelector': 'div.news-content-holder > h3 > a > span',
            'linkSelector': 'div.news-content-holder > h3 > a',
            'dateSelector': 'div.post-date > span',
            'fileName': 'erciyes_fakulte_egitim_egitim_bilimleri.json',
        },
        {
            'name': 'Matematik ve Fen Bilimleri',
            'url': 'http://matfen.egitim.erciyes.edu.tr',
            'startingLink': 'http://matfen.egitim.erciyes.edu.tr',
            'titleSelector': 'div.news-content-holder > h3 > a > span',
            'linkSelector': 'div.news-content-holder > h3 > a',
            'dateSelector': 'div.post-date > span',
            'fileName': 'erciyes_fakulte_egitim_mat_fen_bilimleri.json',
        },
        {
            'name': 'Temel Eğitim',
            'url': 'http://temeg.egitim.erciyes.edu.tr',
            'startingLink': 'http://temeg.egitim.erciyes.edu.tr',
            'titleSelector': 'div.news-content-holder > h3 > a > span',
            'linkSelector': 'div.news-content-holder > h3 > a',
            'dateSelector': 'div.post-date > span',
            'fileName': 'erciyes_fakulte_egitim_temel_egitim.json',
        },
        {
            'name': 'Türkçe ve Sosyal Bilimler',
            'url': 'http://trsos.egitim.erciyes.edu.tr',
            'startingLink': 'http://trsos.egitim.erciyes.edu.tr',
            'titleSelector': 'div.news-content-holder > h3 > a > span',
            'linkSelector': 'div.news-content-holder > h3 > a',
            'dateSelector': 'div.post-date > span',
            'fileName': 'erciyes_fakulte_egitim_turkce_sosyal_bilimler.json',
        },
        {
            'name': 'Yabancı Diller',
            'url': 'http://dil.egitim.erciyes.edu.tr/?id=000026',
            'startingLink': 'http://dil.egitim.erciyes.edu.tr',
            'titleSelector': 'div.news-content-holder > h3 > a > span',
            'linkSelector': 'div.news-content-holder > h3 > a',
            'dateSelector': 'div.post-date > span',
            'fileName': 'erciyes_fakulte_egitim_yabanci_diller.json',
        },
        {
            'name': 'Özel Eğitim',
            'url': 'http://ozel.egitim.erciyes.edu.tr/?id=000027',
            'startingLink': 'http://ozel.egitim.erciyes.edu.tr',
            'titleSelector': 'div.news-content-holder > h3 > a > span',
            'linkSelector': 'div.news-content-holder > h3 > a',
            'dateSelector': 'div.post-date > span',
            'fileName': 'erciyes_fakulte_egitim_ozel_egitim.json',
        },
        {
            'name': 'Fen Fakültesi',
            'url': 'http://fen.erciyes.edu.tr',
            'startingLink': 'http://fen.erciyes.edu.tr',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_fakulte_fen.json',
        },
        {
            'name': 'Güzel Sanatlar Fakültesi',
            'url': 'http://guzelsanat.erciyes.edu.tr',
            'startingLink': 'http://guzelsanat.erciyes.edu.tr/',
            'titleSelector': 'div.card-body > h3 > a',
            'linkSelector': 'div.card-body > h3 > a',
            'dateSelector': 'div.card-head > div.card-stamp > a',
            'fileName': 'erciyes_fakulte_guzel_sanatlar.json',
        },
        {
            'name': 'Havacılık Fakültesi',
            'url': 'https://havacilik.erciyes.edu.tr/',
            'startingLink': 'https://havacilik.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_fakulte_havacilik.json',
        },
        {
            'name': 'Hukuk Fakültesi',
            'url': 'https://hukuk.erciyes.edu.tr/',
            'startingLink': 'https://hukuk.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_fakulte_hukuk.json',
        },
        {
            'name': 'İktisadi ve İdari Bilimler Fakültesi',
            'url': 'http://iibf.erciyes.edu.tr',
            'startingLink': 'http://iibf.erciyes.edu.tr/',
            'titleSelector': 'div.Categories > ul > li > a > font',
            'linkSelector': 'div.Categories > ul > li > a',
            'dateSelector': 'div.Categories > ul > li > span.label',
            'fileName': 'erciyes_fakulte_iibf.json',
        },
        {
            'name': 'İlahiyat Fakültesi',
            'url': 'https://ilahiyat.erciyes.edu.tr/',
            'startingLink': 'https://ilahiyat.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_fakulte_ilahiyat.json',
        },
        {
            'name': 'İletişim Fakültesi',
            'url': 'http://iletisim.erciyes.edu.tr/category/duyuru/',
            'startingLink': '',
            'titleSelector': 'div.post-info > h2 > a',
            'linkSelector': 'div.post-info > h2 > a',
            'dateSelector': 'div.post-info > p.postmetadata',
            'fileName': 'erciyes_fakulte_iletisim.json',
        },
        {
            'name': 'Mimarlık Fakültesi',
            'url': 'http://mimarlik.erciyes.edu.tr',
            'startingLink': 'http://mimarlik.erciyes.edu.tr',
            'titleSelector': 'div.duyurugenislik2 > a',
            'linkSelector': 'div.duyurugenislik2 > a',
            'dateSelector': 'div > div[style|=font]',
            'dateSelector2': 'div > div[style|=margin]',
            'fileName': 'erciyes_fakulte_mimarlik.json',
        },
        {
            'name': 'Sağlık Bilimleri Fakültesi',
            'url': 'https://sbf.erciyes.edu.tr/',
            'startingLink': 'https://sbf.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_fakulte_saglik_bilimleri.json',
        },
        {
            'name': 'Seyrani Ziraat Fakültesi',
            'url': 'https://ziraat.erciyes.edu.tr/',
            'startingLink': 'https://ziraat.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_fakulte_seyrani_ziraat.json',
        },
        {
            'name': 'Spor Bilimleri Fakültesi',
            'url': 'https://spbf.erciyes.edu.tr/',
            'startingLink': 'https://spbf.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_fakulte_spor_bilimleri.json',
        },
        {
            'name': 'Tıp Fakültesi',
            'url': 'http://tip.erciyes.edu.tr/bizden-duyurular.html',
            'startingLink': 'http://tip.erciyes.edu.tr/',
            'titleSelector': 'div.irs-courses-content > h4 > a',
            'linkSelector': 'div.irs-courses-content > h4 > a',
            'dateSelector': 'li > p > a',
            'fileName': 'erciyes_fakulte_tip.json',
        },
        {
            'name': 'Turizm Fakültesi',
            'url': 'https://turizm.erciyes.edu.tr',
            'startingLink': 'http://turizm.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'span.img > span.gun',
            'dateSelector2': 'span.img > span.ay',
            'dateSelector3': 'span.img > span.yil',
            'fileName': 'erciyes_fakulte_turizm.json',
        },
        {
            'name': 'Veteriner Fakültesi',
            'url': 'https://veteriner.erciyes.edu.tr',
            'startingLink': 'https://veteriner.erciyes.edu.tr/',
            'titleSelector': 'div.profile-post-in > h3.heading-xs > a',
            'linkSelector': 'div.profile-post-in > h3.heading-xs > a',
            'dateSelector': 'div.profile-post > span.profile-post-numb',
            'fileName': 'erciyes_fakulte_veteriner.json',
        },
        {
            'name': 'Erasmus Duyuruları',
            'url': 'https://erasmus.erciyes.edu.tr/duyurular.asp',
            'startingLink': 'https://erasmus.erciyes.edu.tr/',
            'titleSelector': 'div[style|=font] > a.link1',
            'linkSelector': 'div[style|=font] > a.link1',
            'dateSelector': '.ana_div div div div div div a i',
            'listBoundary': '5',
            'fileName': 'erciyes_website_erasmus.json',
        },
        {
            'name': 'Obisis Duyuruları',
            'url': 'https://obisis.erciyes.edu.tr',
            'startingLink': '',
            'titleSelector': 'tr > td > span.NormalBlue',
            'linkSelector': '',
            'fileName': 'erciyes_website_obisis.json',
        },
        {
            'name': 'Adalet Meslek Yüksekokulu',
            'url': 'https://adalet.erciyes.edu.tr',
            'startingLink': 'https://adalet.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_myo_adalet.json',
        },
        {
            'name': 'Halil Bayraktar... Yüksekokulu',
            'url': 'https://hbshmyo.erciyes.edu.tr',
            'startingLink': 'https://hbshmyo.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_myo_halil_bayraktar.json',
        },
        {
            'name': 'Yabancı Diller Yüksekokulu',
            'url': 'http://ydyo.erciyes.edu.tr',
            'startingLink': 'http://ydyo.erciyes.edu.tr',
            'titleSelector': 'h6 > a',
            'linkSelector': 'h6 > a',
            'dateSelector': 'div.course > span',
            'fileName': 'erciyes_yo_yabanci_diller.json',
        },
        {
            'name': 'Atatürk İlkeleri ve İnkılap Tarihi Enstitüsü',
            'url': 'https://aiite.erciyes.edu.tr',
            'startingLink': 'https://aiite.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_enstitu_ataturk_ilkeleri_tarihi.json',

        },
        {
            'name': 'Fen Bilimleri Enstitüsü',
            'url': 'https://fbe.erciyes.edu.tr',
            'startingLink': 'https://fbe.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_enstitu_fen_bilimleri.json',
        },
        {
            'name': 'Gevher Nesibe Genom ve Kök Hücre Enstitüsü',
            'url': 'https://gevhernesibe.erciyes.edu.tr',
            'startingLink': 'https://gevhernesibe.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_enstitu_gevher_nesibe.json',
        },
        {
            'name': 'Güzel Sanatlar Enstitüsü',
            'url': 'https://gse.erciyes.edu.tr',
            'startingLink': 'https://gse.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_enstitu_guzel_sanatlar.json',
        },
        {
            'name': 'Sosyal Bilimler Enstitüsü',
            'url': 'https://sbe.erciyes.edu.tr',
            'startingLink': 'https://sbe.erciyes.edu.tr/',
            'titleSelector': 'li > span.aciklama > a',
            'linkSelector': 'li > span.aciklama > a',
            'dateSelector': 'li > span.img > span.gun',
            'dateSelector2': 'li > span.img > span.ay',
            'dateSelector3': 'li > span.img > span.yil',
            'fileName': 'erciyes_enstitu_sosyal_bilimler.json',
        },
        {
            'name': 'Eğitim Bilimleri Ensitüsü',
            'url': 'https://ebil.erciyes.edu.tr/dosya.asp?bolum=dosyalar&menu=1&dili=turkce&sayfabasi=DUYURU%20ve%20HABERLER',
            'startingLink': 'https://ebil.erciyes.edu.tr/',
            'titleSelector': 'td > a',
            'linkSelector': 'td > a',
            'dateSelector': 'div.date',
            'fileName': 'erciyes_enstitu_egitim_bilimleri.json',
        },
        {
            'name': 'Farabi Duyuruları',
            'url': 'https://farabi.erciyes.edu.tr/0/Erciyes-Universitesi-Farabi-Degisim-Programı/Tum-Duyurular',
            'startingLink': 'https://farabi.erciyes.edu.tr',
            'titleSelector': 'td > div > a',
            'linkSelector': 'td > div > a',
            'dateSelector': 'td > div > span',
            'fileName': 'erciyes_website_farabi.json',
        },
        {
            'name': 'Mevlana Duyuruları',
            'url': 'https://mevlana.erciyes.edu.tr/Mevlana-Degisim-Programi/Duyurular',
            'startingLink': '',
            'titleSelector': 'td > div.duyuruSatir > span > a',
            'linkSelector': 'td > div.duyuruSatir > span > a',
            'fileName': 'erciyes_website_mevlana.json',
        },
        {
            'name': 'Erciyes Üniversitesi Anasayfası',
            'url': 'https://www.erciyes.edu.tr/Tum-Duyurular/0',
            'startingLink': 'https://www.erciyes.edu.tr',
            'titleSelector': 'div.container > div.row > div > a',
            'linkSelector': 'div.container > div.row > div > a',
            'dateSelector': 'div.container > div.row > div > span',
            'fileName': 'erciyes_anasayfa.json',
        },
        {
            'name': 'Öğrenci İşleri',
            'url': 'https://ogrisl.erciyes.edu.tr',
            'startingLink': 'https://ogrisl.erciyes.edu.tr',
            'titleSelector': 'div.DuyuruSatirlar > ul > li > a',
            'linkSelector': 'div.DuyuruSatirlar > ul > li > a',
            'dateSelector': 'div.DuyuruSatirlar > ul > li > i',
            'fileName': 'erciyes_website_ogrenci_isleri.json',
        },
        {
            'name': 'Eruzem',
            'url': 'http://eruzem.erciyes.edu.tr/tr/tum-duyurular',
            'startingLink': 'http://eruzem.erciyes.edu.tr',
            'titleSelector': 'div.tt-cours-info > a',
            'linkSelector': 'div.tt-cours-info > a',
            'fileName': 'erciyes_website_eruzem.json',
        },
    ]
